local g = vim.g
local highlight = vim.api.nvim_set_hl

local black = "#101010"
local white = "#F6FAFA"
local bg = black

local grey0 = "#245668"
local grey1 = "#373c4d"
local grey89 = "#e4e4e4"
local grey70 = "#b2b2b2"
local grey62 = "#9e9e9e"
local grey58 = "#949494"
local grey50 = "#808080"
local grey39 = "#626262"
local grey30 = "#4e4e4e"
local grey27 = "#444444"
local grey23 = "#3a3a3a"
local grey18 = "#2e2e2e"
local grey15 = "#262626"
local grey11 = "#1c1c1c"
local grey7 = "#121212"

-- Core theme
local khaki = "#f9cb52"
local yellow = "#e4ba4e"
local orange = "#de935f"
local lightorange = "#E2C7B6"
local coral = "#f09479"
local orchid = "#e196a2"
local lime = "#99da3d"
local green = "#6fcf25"
local lightgreen = "#8FCF6C"
local emerald = "#36c692"
local turquoise = "#7fd3a5"
local blue = "#2188EF"
local lightblue = "#4DB9F4"
local sky = "#7FB7EF"
local lavender = "#adadf3"
local purple = "#9215EB"
local pink = "#FF7D7D"
local violet = "#E061F9"
local cranberry = "#e65e72"
local crimson = "#ff5189"
local red = "#ff5454"
local magenta = "#FF03F2"
local magenta2 = "#B31DAB"

-- Extra
local sand = "#EFDB8A"
local ochre = "#eac290"
local alarm = "#f9bc05"
local alarmred = "#fe1808"
local colorcolumn = "#0A0A0A"

local M = {}

M.style = function()
  -- Basics
  highlight(0, "Normal", { bg = bg, fg = white })
  highlight(0, "ModeMsg", { fg = sand })
  highlight(0, "Comment", { fg = grey62, italic = true })

  highlight(0, "Pmenu", { bg = bg, fg = white })

  -- Basic syntax highlighting
  highlight(0, "Constant", { fg=coral })
  highlight(0, "String", { fg=khaki })
  highlight(0, "Character", { fg=lightorange })
  highlight(0, "Number", { fg=coral })
  highlight(0, "Boolean", { fg=blue, bold=1 })
  highlight(0, "Float", { fg=sky })
  highlight(0, "Identifier", { fg=lightblue })
  highlight(0, "Function", { fg=sand })
  highlight(0, "Statement", { fg=lime, bold=1 })
  highlight(0, "Conditional", { fg=green, bold=1 })
  highlight(0, "Repeat", { fg=green, bold=1 })
  highlight(0, "Label", { fg=sand })
  highlight(0, "Opterator", { fg=white })
  highlight(0, "Keyword", { fg=lime, bold=1 })
  highlight(0, "Exception", { fg=lime, bold=1 })

  highlight(0, "PreProc", { fg=khaki })
  highlight(0, "Include", { fg=sand })
  highlight(0, "Define", { fg=yellow })
  highlight(0, "Macro", { fg=ochre })
  highlight(0, "PreCondit", { fg=orange })

  highlight(0, "Type", { fg=turquoise })
  highlight(0, "StorageClass", { fg=lightblue })
  highlight(0, "Structure", { fg=sky, bold=1 })
  highlight(0, "Typedef", { fg=blue, bold=1 })

  highlight(0, "Underlined", { fg=white, underline=true })
  highlight(0, "Error", { bg=alarmred, fg=white, bold=1 })
  highlight(0, "Todo", { bg=alarm, fg=black, bold=1 })

  -- UI
  highlight(0, "Normal", { fg=white, bg=black })
  highlight(0, "ColorColumn", { bg=colorcolumn, fg=white, bold=1 })
  highlight(0, "ErrorMsg", { fg=red })
  highlight(0, "VertSplit", { bg=grey18, fg=black })
  highlight(0, "LineNr", { fg=grey27 })
  highlight(0, "Whitespace", { fg=magenta })
  highlight(0, "CurSearch", { fg=white, bg=magenta })
  highlight(0, "EndOfBuffer", { fg=magenta2 })
  highlight(0, "WinSeparator", { fg=grey15, bg=grey15 })

  -- C
  highlight(0, "cStatement", {})
  highlight(0, "cLabel", {})
  highlight(0, "cConditional", {})
  highlight(0, "cRepeat", {})
  highlight(0, "cTodo", {})
  highlight(0, "cBadContinuation", {})
  highlight(0, "cSpecial", { fg=orange })
  highlight(0, "cFormat", { fg=orange })
  highlight(0, "cString", {})
  highlight(0, "cCppString", {})
  highlight(0, "cSpaceError", {})
  highlight(0, "cCppSkip", {})
  highlight(0, "cCharacter", {})
  highlight(0, "cSpecialError", {})
  highlight(0, "cSpecialCharacter", {})
  highlight(0, "cBadBlock", {})
  highlight(0, "cCurlyError", {})
  highlight(0, "cErrInParen", {})
  highlight(0, "cCppParen", {})
  highlight(0, "cErrInBracket", {})
  highlight(0, "cCppBracket", {})
  highlight(0, "cBlock", {})
  highlight(0, "cParenError", {})
  highlight(0, "cIncluded", {})
  highlight(0, "cCommentSkip", {})
  highlight(0, "cCommentString", {})
  highlight(0, "cComment2String", {})
  highlight(0, "cCommentStartError", {})
  highlight(0, "cUserLabel", {})
  highlight(0, "cBitField", {})
  highlight(0, "cOctalZero", {})
  highlight(0, "cNumber", {})
  highlight(0, "cFloat", {})
  highlight(0, "cOctal", {})
  highlight(0, "cOctalError", {})
  highlight(0, "cNumbersCom", {})
  highlight(0, "cParen", {})
  highlight(0, "cBracket", {})
  highlight(0, "cNumbers", {})
  highlight(0, "cWrongComTail", {})
  highlight(0, "cCommentL", {})
  highlight(0, "cCommentStart", {})
  highlight(0, "cComment", {})
  highlight(0, "cCommentError", {})
  highlight(0, "cOperator", {})
  highlight(0, "cType", {})
  highlight(0, "cTypedef", {})
  highlight(0, "cStructure", {})
  highlight(0, "cStorageClass", {})
  highlight(0, "cConstant", {})
  highlight(0, "cPreCondit", {})
  highlight(0, "cPreConditMatch", {})
  highlight(0, "cCppInIf", {})
  highlight(0, "cCppInElse", {})
  highlight(0, "cCppInElse2", {})
  highlight(0, "cCppOutIf", {})
  highlight(0, "cCppOutIf2", {})
  highlight(0, "cCppOutElse", {})
  highlight(0, "cCppInSkip", {})
  highlight(0, "cCppOutSkip", {})
  highlight(0, "cCppOutWrapper", {})
  highlight(0, "cCppInWrapper", {})
  highlight(0, "cPreProc", {})
  highlight(0, "cInclude", { fg=lightorange })
  highlight(0, "cDefine", {})
  highlight(0, "cMulti", {})
  highlight(0, "cPragma", {})
  highlight(0, "cUserCont", {})
  highlight(0, "cError", {})
  highlight(0, "cCppOut", {})
  highlight(0, "cUserFunction", {})
  highlight(0, "cStructMember", {})

  -- CPP
  highlight(0, "cppStatement", {})
  highlight(0, "cppAccess", {})
  highlight(0, "cppModifier", {})
  highlight(0, "cppType", {})
  highlight(0, "cppExceptions", {})
  highlight(0, "cppOperator", {})
  highlight(0, "cppCast", {})
  highlight(0, "cppStorageClass", {})
  highlight(0, "cppStructure", {})
  highlight(0, "cppBoolean", {})
  highlight(0, "cppConstant", {})
  highlight(0, "cppRawStringDelimiter", {})
  highlight(0, "cppRawString", {})
  highlight(0, "cppNumber", {})
  highlight(0, "cppFloat", {})
  highlight(0, "cppNumbers", {})
  highlight(0, "cppString", {})
  highlight(0, "cppCharacter", {})
  highlight(0, "cppSpecialError", {})
  highlight(0, "cppSpecialCharacter", {})
  highlight(0, "cppModule", {})
  highlight(0, "cppMinMax", {})
  highlight(0, "cppSTLdefine", {})
  highlight(0, "cppSTLnamespace", {})
  highlight(0, "cppSTLconstant", {})
  highlight(0, "cppSTLvariable", {})
  highlight(0, "cppSTLexception", {})
  highlight(0, "cppSTLios", {})
  highlight(0, "cppSTLtype", {})
  highlight(0, "cppSTLtypedef", {})
  highlight(0, "cppSTLiterator", {})
  highlight(0, "cppSTLfunction", {})
  highlight(0, "cppSTLenum", {})
  highlight(0, "cppSTLbool", {})
  highlight(0, "cppSTLconcept", {})

  -- GLSL
  highlight(0, "glslConditional", {})
  highlight(0, "glslRepeat", {})
  highlight(0, "glslStatement", {})
  highlight(0, "glslTodo", {})
  highlight(0, "glslCommentL", {})
  highlight(0, "glslCommentStart", {})
  highlight(0, "glslComment", {})
  highlight(0, "glslPreCondit", {})
  highlight(0, "glslDefine", {})
  highlight(0, "glslTokenConcat", {})
  highlight(0, "glslPredefinedMacro", {})
  highlight(0, "glslPreProc", {})
  highlight(0, "glslInclude", {})
  highlight(0, "glslCurlyBlock", {})
  highlight(0, "glslParenBlock", {})
  highlight(0, "glslBoolean", {})
  highlight(0, "glslDecimalInt", {})
  highlight(0, "glslOctalInt", {})
  highlight(0, "glslHexInt", {})
  highlight(0, "glslFloat", {})
  highlight(0, "glslSwizzle", {})
  highlight(0, "glslStructure", {})
  highlight(0, "glslIdentifier", {})
  highlight(0, "glslIdentifierPrime", {})
  highlight(0, "glslType", {})
  highlight(0, "glslQualifier", {})
  highlight(0, "glslBuiltinConstant", {})
  highlight(0, "glslBuiltinVariable", {})
  highlight(0, "glslBuiltinFunction", {})
  highlight(0, "glslInteger", {})

  -- Rust
  highlight(0, "rustConditional", { link="Conditional" })
  highlight(0, "rustRepeat", {})
  highlight(0, "rustKeyword", {})
  highlight(0, "rustTypedef", {})
  highlight(0, "rustIdentifier", {})
  highlight(0, "rustStructure", {})
  highlight(0, "rustUnion", { fg=turquoise })
  highlight(0, "rustUnionContextual", {})
  highlight(0, "rustOperator", { link="Operator" })
  highlight(0, "rustExistential", {})
  highlight(0, "rustExistentialContextual", {})
  highlight(0, "rustAssert", { fg=lightgreen })
  highlight(0, "rustPanic", { fg=crimson })
  highlight(0, "rustAsync", { bold=1})
  highlight(0, "rustExternCrate", {})
  highlight(0, "rustObsoleteExternMod", {})
  highlight(0, "rustFuncName", {})
  highlight(0, "rustPubScope", {})
  highlight(0, "rustSuper", {})
  highlight(0, "rustUnsafeKeyword", {})
  highlight(0, "rustModPath", {})
  highlight(0, "rustStorage", {})
  highlight(0, "rustDefault", {})
  highlight(0, "rustAwait", { fg=turquoise })
  highlight(0, "rustPubScopeCrate", {})
  highlight(0, "rustPubScopeDelim", {})
  highlight(0, "rustModPathSep", {})
  highlight(0, "rustSelf", { fg=turquoise})
  highlight(0, "rustExternCrateString", {})
  highlight(0, "rustString", { link="String"})
  highlight(0, "rustIdentifierPrime", {})
  highlight(0, "rustMacroRepeatDelimiters", {})
  highlight(0, "rustMacroRepeat", {})
  highlight(0, "rustMacroVariable", {})
  highlight(0, "rustRawIdent", {})
  highlight(0, "rustReservedKeyword", {})
  highlight(0, "rustType", { fg=lightblue })
  highlight(0, "rustTrait", {})
  highlight(0, "rustEnum", {})
  highlight(0, "rustEnumVariant", {})
  highlight(0, "rustBoolean", {})
  highlight(0, "rustFuncCall", {})
  highlight(0, "rustSigil", {})
  highlight(0, "rustArrowCharacter", {})
  highlight(0, "rustQuestionMark", { fg=orange })
  highlight(0, "rustMacro", {})
  highlight(0, "rustEscapeError", {})
  highlight(0, "rustEscape", { fg=orange })
  highlight(0, "rustEscapeUnicode", {})
  highlight(0, "rustStringContinuation", {})
  highlight(0, "rustStringDelimiter", {})
  highlight(0, "rustAttributeParenthesizedParens", {})
  highlight(0, "rustAttributeParenthesizedCurly", {})
  highlight(0, "rustAttributeParenthesizedBrackets", {})
  highlight(0, "rustDerive", {})
  highlight(0, "rustAttribute", {})
  highlight(0, "rustAttributeBalancedParens", {})
  highlight(0, "rustAttributeBalancedCurly", {})
  highlight(0, "rustAttributeBalancedBrackets", {})
  highlight(0, "rustCommentLine", { link="Comment" })
  highlight(0, "rustCommentBlock", { link="Comment" })
  highlight(0, "rustCommentLineDocError", { link="Comment" })
  highlight(0, "rustCommentBlockDocError", { link="Comment" })
  highlight(0, "rustDeriveTrait", {})
  highlight(0, "rustDynKeyword", {})
  highlight(0, "rustDecNumber", { link="Number"})
  highlight(0, "rustHexNumber", { link="Number" })
  highlight(0, "rustOctNumber", { link="Number" })
  highlight(0, "rustBinNumber", { link="Number" })
  highlight(0, "rustFloat", { link="Number" })
  highlight(0, "rustLifetime", {})
  highlight(0, "rustLifetimeCandidate", {})
  highlight(0, "rustGenericLifetimeCandidate", {})
  highlight(0, "rustGenericRegion", {})
  highlight(0, "rustLabel", {})
  highlight(0, "rustCharacterInvalid", {})
  highlight(0, "rustCharacterInvalidUnicode", {})
  highlight(0, "rustCharacter", {})
  highlight(0, "rustShebang", { fg=pink})
  highlight(0, "rustTodo", { link="Todo" })
  highlight(0, "rustCommentLineDoc", { link="Comment" })
  highlight(0, "rustCommentBlockNest", { link="Comment" })
  highlight(0, "rustCommentBlockDoc", { link="Comment" })
  highlight(0, "rustCommentBlockDocNest", { link="Comment" })
  highlight(0, "rustCommentBlockDocRustCode", { link="Comment" })
  highlight(0, "rustCommentBlockDocNestError", { link="Comment" })
  highlight(0, "rustAsmDirSpec", {})
  highlight(0, "rustAsmSym", {})
  highlight(0, "rustAsmConst", {})
  highlight(0, "rustAsmOptionsGroup", {})
  highlight(0, "rustAsmMacro", {})
  highlight(0, "rustAsmReg", {})
  highlight(0, "rustAsmSymPath", {})
  highlight(0, "rustAsmConstBalancedParens", {})
  highlight(0, "rustAsmOptions", {})
  highlight(0, "rustAsmOptionsKey", {})
  highlight(0, "rustFoldBraces", {})
  highlight(0, "rustCommentLineDocLeader", { link="Comment" })
  highlight(0, "rustCommentBlockDocStar", { link="Comment" })
  highlight(0, "rustNumber", {})
  highlight(0, "rustConstant", {})
  highlight(0, "rustCapsIdent", {})
  highlight(0, "rustFunction", { link="Function" })
  highlight(0, "rustCommentDocCodeFence", { link="Comment" })
  highlight(0, "rustObsoleteStorage", {})
  highlight(0, "rustCommentLinesDocNonRustCode", { link="Comment" })
  highlight(0, "rustCommentLinesDocRustCode", { link="Comment" })

  -- Python
  highlight(0, "pythonFunctionCall", {})
  highlight(0, "pythonStatement", {})
  highlight(0, "pythonExClass", {})
  highlight(0, "pythonFunction", {})
  highlight(0, "pythonClass", {})
  highlight(0, "pythonClassVar", {})
  highlight(0, "pythonRepeat", {})
  highlight(0, "pythonConditional", {})
  highlight(0, "pythonException", {})
  highlight(0, "pythonInclude", {})
  highlight(0, "pythonImport", {})
  highlight(0, "pythonRaiseFromStatement", {})
  highlight(0, "pythonOperator", {fg=lightblue, bold=1})
  highlight(0, "pythonNumber", {})
  highlight(0, "pythonHexNumber", {})
  highlight(0, "pythonOctNumber", {})
  highlight(0, "pythonBinNumber", {})
  highlight(0, "pythonFloat", {})
  highlight(0, "pythonString", {})
  highlight(0, "pythonFString", {  })
  highlight(0, "pythonRawString", {})
  highlight(0, "pythonRawFString", {})
  highlight(0, "pythonBytes", {})
  highlight(0, "pythonBoolean", {})
  highlight(0, "pythonNone", {})
  highlight(0, "pythonSingleton", {})
  highlight(0, "pythonBuiltinObj", {})
  highlight(0, "pythonBuiltinFunc", {})
  highlight(0, "pythonBuiltinType", {})
  highlight(0, "pythonError", {fg=magenta, bold=1})
  highlight(0, "pythonDottedName", {})
  highlight(0, "pythonDecorator", {})
  highlight(0, "pythonDot", {})
  highlight(0, "pythonTodo", {})
  highlight(0, "pythonComment", {})
  highlight(0, "pythonIndentError", {})
  highlight(0, "pythonSpaceError", { fg=magenta })
  highlight(0, "pythonBytesEscape", { fg=orange })
  highlight(0, "pythonBytesEscapeError", {})
  highlight(0, "pythonUniEscape", {})
  highlight(0, "pythonUniEscapeError", {})
  highlight(0, "pythonDocTest2", {})
  highlight(0, "pythonDocTest", {})
  highlight(0, "pythonBytesError", {})
  highlight(0, "pythonBytesContent", {})
  highlight(0, "pythonRawEscape", {})
  highlight(0, "pythonUniRawEscape", {})
  highlight(0, "pythonUniRawEscapeError", {})
  highlight(0, "pythonRawBytes", {})
  highlight(0, "pythonUniString", {})
  highlight(0, "pythonUniRawString", {})
  highlight(0, "pythonStrFormatting", { fg=orange })
  highlight(0, "pythonStrFormat", { fg=orange })
  highlight(0, "pythonStrInterpRegion", {})
  highlight(0, "pythonStrTemplate", {})
  highlight(0, "pythonOctError", {})
  highlight(0, "pythonHexError", {})
  highlight(0, "pythonBinError", {})
  highlight(0, "pythonNumberError", {})

  -- Lualine

  -- CMake
  highlight(0, "cmakeTodo", {})
  highlight(0, "cmakeBracketArgument", {})
  highlight(0, "cmakeComment", {})
  highlight(0, "cmakeBracketComment", {})
  highlight(0, "cmakeEscaped", {})
  highlight(0, "cmakeRegistry", {})
  highlight(0, "cmakeVariableValue", {})
  highlight(0, "cmakeProperty", {})
  highlight(0, "cmakeGeneratorExpressions", {})
  highlight(0, "cmakeGeneratorExpression", {})
  highlight(0, "cmakeString", {})
  highlight(0, "cmakeVariable", {})
  highlight(0, "cmakeEnvironment", {})
  highlight(0, "cmakeCommand", {})
  highlight(0, "cmakeCommandConditional", {})
  highlight(0, "cmakeCommandRepeat", {})
  highlight(0, "cmakeCommandDeprecated", {})
  highlight(0, "cmakeCommandManuallyAdded", {})
  highlight(0, "cmakeArguments", {})
  highlight(0, "cmakeModule", {})
  highlight(0, "cmakeKWExternalProject", {})
  highlight(0, "cmakeKWadd_compile_definitions", {})
  highlight(0, "cmakeKWadd_compile_options", {})
  highlight(0, "cmakeKWadd_custom_command", {})
  highlight(0, "cmakeKWadd_custom_target", {})
  highlight(0, "cmakeKWadd_definitions", {})
  highlight(0, "cmakeKWadd_dependencies", {})
  highlight(0, "cmakeKWadd_executable", {})
  highlight(0, "cmakeKWadd_library", {})
  highlight(0, "cmakeKWadd_link_options", {})
  highlight(0, "cmakeKWadd_subdirectory", {})
  highlight(0, "cmakeKWadd_test", {})
  highlight(0, "cmakeKWbuild_command", {})
  highlight(0, "cmakeKWcmake_host_system_information", {})
  highlight(0, "cmakeKWcmake_language", {})
  highlight(0, "cmakeKWcmake_minimum_required", {})
  highlight(0, "cmakeKWcmake_parse_arguments", {})
  highlight(0, "cmakeKWcmake_path", {})
  highlight(0, "cmakeKWcmake_policy", {})
  highlight(0, "cmakeKWconfigure_file", {})
  highlight(0, "cmakeKWcreate_test_sourcelist", {})
  highlight(0, "cmakeKWctest_build", {})
  highlight(0, "cmakeKWctest_configure", {})
  highlight(0, "cmakeKWctest_coverage", {})
  highlight(0, "cmakeKWctest_memcheck", {})
  highlight(0, "cmakeKWctest_run_script", {})
  highlight(0, "cmakeKWctest_start", {})
  highlight(0, "cmakeKWctest_submit", {})
  highlight(0, "cmakeKWctest_test", {})
  highlight(0, "cmakeKWctest_update", {})
  highlight(0, "cmakeKWctest_upload", {})
  highlight(0, "cmakeKWdefine_property", {})
  highlight(0, "cmakeKWdoxygen_add_docs", {})
  highlight(0, "cmakeKWenable_language", {})
  highlight(0, "cmakeKWenable_testing", {})
  highlight(0, "cmakeKWexec_program", {})
  highlight(0, "cmakeKWexecute_process", {})
  highlight(0, "cmakeKWexport", {})
  highlight(0, "cmakeKWexport_library_dependencies", {})
  highlight(0, "cmakeKWfile", {})
  highlight(0, "cmakeKWfind_file", {})
  highlight(0, "cmakeKWfind_library", {})
  highlight(0, "cmakeKWfind_package", {})
  highlight(0, "cmakeKWfind_path", {})
  highlight(0, "cmakeKWfind_program", {})
  highlight(0, "cmakeKWfltk_wrap_ui", {})
  highlight(0, "cmakeKWforeach", {})
  highlight(0, "cmakeKWfunction", {})
  highlight(0, "cmakeKWget_cmake_property", {})
  highlight(0, "cmakeKWget_directory_property", {})
  highlight(0, "cmakeKWget_filename_component", {})
  highlight(0, "cmakeKWget_property", {})
  highlight(0, "cmakeKWget_source_file_property", {})
  highlight(0, "cmakeKWget_target_property", {})
  highlight(0, "cmakeKWget_test_property", {})
  highlight(0, "cmakeKWif", {})
  highlight(0, "cmakeKWinclude", {})
  highlight(0, "cmakeKWinclude_directories", {})
  highlight(0, "cmakeKWinclude_external_msproject", {})
  highlight(0, "cmakeKWinclude_guard", {})
  highlight(0, "cmakeKWinstall", {})
  highlight(0, "cmakeKWinstall_files", {})
  highlight(0, "cmakeKWinstall_programs", {})
  highlight(0, "cmakeKWinstall_targets", {})
  highlight(0, "cmakeKWlink_directories", {})
  highlight(0, "cmakeKWlist", {})
  highlight(0, "cmakeKWload_cache", {})
  highlight(0, "cmakeKWload_command", {})
  highlight(0, "cmakeKWmacro", {})
  highlight(0, "cmakeKWmark_as_advanced", {})
  highlight(0, "cmakeKWmath", {})
  highlight(0, "cmakeKWmessage", {})
  highlight(0, "cmakeKWoption", {})
  highlight(0, "cmakeKWproject", {})
  highlight(0, "cmakeKWqt_wrap_cpp", {})
  highlight(0, "cmakeKWqt_wrap_ui", {})
  highlight(0, "cmakeKWremove", {})
  highlight(0, "cmakeKWreturn", {})
  highlight(0, "cmakeKWseparate_arguments", {})
  highlight(0, "cmakeKWset", {})
  highlight(0, "cmakeKWset_directory_properties", {})
  highlight(0, "cmakeKWset_property", {})
  highlight(0, "cmakeKWset_source_files_properties", {})
  highlight(0, "cmakeKWset_target_properties", {})
  highlight(0, "cmakeKWset_tests_properties", {})
  highlight(0, "cmakeKWsite_name", {})
  highlight(0, "cmakeKWsource_group", {})
  highlight(0, "cmakeKWstring", {})
  highlight(0, "cmakeKWsubdirs", {})
  highlight(0, "cmakeKWtarget_compile_definitions", {})
  highlight(0, "cmakeKWtarget_compile_features", {})
  highlight(0, "cmakeKWtarget_compile_options", {})
  highlight(0, "cmakeKWtarget_include_directories", {})
  highlight(0, "cmakeKWtarget_link_directories", {})
  highlight(0, "cmakeKWtarget_link_libraries", {})
  highlight(0, "cmakeKWtarget_link_options", {})
  highlight(0, "cmakeKWtarget_precompile_headers", {})
  highlight(0, "cmakeKWtarget_sources", {})
  highlight(0, "cmakeKWtry_compile", {})
  highlight(0, "cmakeKWtry_run", {})
  highlight(0, "cmakeKWunset", {})
  highlight(0, "cmakeKWuse_mangled_mesa", {})
  highlight(0, "cmakeKWvariable_requires", {})
  highlight(0, "cmakeKWvariable_watch", {})
  highlight(0, "cmakeKWwrite_file", {})
  highlight(0, "cmakeKWconfigure_package_config_file", {})
  highlight(0, "cmakeKWconfigure_package_config_file_constants", {})
  highlight(0, "cmakeKWwrite_basic_package_version_file", {})

  -- json
  highlight(0, "jsonNoise", {})
  highlight(0, "jsonString", {})
  highlight(0, "jsonStringMatch", {})
  highlight(0, "jsonEscape", {})
  highlight(0, "jsonQuote", {})
  highlight(0, "jsonStringSQError", {})
  highlight(0, "jsonKeyword", {})
  highlight(0, "jsonKeywordMatch", {})
  highlight(0, "jsonNumber", {})
  highlight(0, "jsonNoQuotesError", {})
  highlight(0, "jsonTripleQuotesError", {})
  highlight(0, "jsonNumError", {})
  highlight(0, "jsonCommentError", {})
  highlight(0, "jsonSemicolonError", {})
  highlight(0, "jsonTrailingCommaError", {})
  highlight(0, "jsonMissingCommaError", {})
  highlight(0, "jsonPadding", {})
  highlight(0, "jsonBoolean", {})
  highlight(0, "jsonNull", {})
  highlight(0, "jsonBraces", {})
  highlight(0, "jsonFold", {})
  highlight(0, "jsonTest", {})

end

return M
